config/routes.rb
Rails.application.routes.draw do
  root :to => 'tops#index'
  get 'news/index'
  get 'news/show'
  get 'tops/faq'
  get 'tops/work'
  get 'tops/price'
  get 'tops/function'

  resources :contacts, :only => [:new, :create] do
    collection do
      post :preview
      get :thanks
    end
  end

  namespace :ar_admin do
    root :to => 'admin#index'
    resources :information_statuses, :except => [:new, :show]

    resources :informations do
      member do
        put :sort_up, :sort_down
      end
    end

    resources :faqs do
      member do
        put :sort_up, :sort_down
      end
    end    

    resources :faq_categories , :only => [:index, :new, :create, :edit, :update, :destroy] do
      member do
         put :sort_up, :sort_down
      end
    end

    # put 'faq_categories/sort_up'
    # put 'faq_categories/sort_down'

    resources :function_infos do
      member do
        put :sort_up, :sort_down
      end
    end

    resources :contacts, :only => [:index, :show] do
      collection do
        post :update_status
      end
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @informations = Information.all
  end

  def show
  	@informations = Information.all.limit(3)
  	@information = Information.find(params[:id])

  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_information_list.html.erb
<ul class="clearfix">
  <% @informations.each do |info| %>
  	<li class="clearfix">
  		<div class="image">
  		  <%= link_to info.title, news_show_path(:id => info.id), :style => "background-image: url(#{image_path info.image})" %>
      </div>


      <h3><%= link_to info.title, news_show_path(:id => info.id) %></h3>
      <div class="desc"><%= info.content.truncate(80) %></div>
  		<p class="update"><%= info.updated_at.strftime("%Y.%-m.%-d") %></p>
  		<p class="link"><%= link_to 'MORE', news_show_path(:id => info.id) %></p>
  	</li>
  <% end %>
</ul>

app/views/news/index.html.erb
<body>
  <div id="wrapper">
    <%= render '/header' %>
    <!-- コンテンツ開始 -->
    <article id="content">
      <section id="news" class="news_list_box clearfix">
        <div id="news_lists"><%= render 'information_list' %></div>
        <div class="more"><%= link_to_next_page @informations, 'もっと見る', remote: true, id: 'more_link' %></div>
      </section>
    </article>
    <!-- コンテンツ終了 -->
    <%= render '/footer' %>
  </div>
</body>

app/views/news/index.js.erb
<%#
  #　お知らせ用もっとみるJS
%>
$('#news_lists').append("<%= escape_javascript(render 'information_list', object: @informations) %>");
$("#view_more").replaceWith("<%= escape_javascript(link_to_next_page(@informations, 'もっと見る', remote: true, id: 'view_more')) %>");

app/views/news/show.html.erb
<body>
  <div id="wrapper">
    <%= render '/header' %>
    <!-- コンテンツ開始 -->
    <article id="content">
      <section id="news_detail" class="news_box clearfix">

        <p class="update"><%= @information.updated_at.strftime("%Y.%-m.%-d") %> </p>
        <div class="head">
          <h3><%= @information.title %></h3>
        </div>
        <figure class="image"><%= image_tag @information.image.to_s, width: "1900", height: "1160", alt: "" %></figure>
        <div class="desc">
          <%= @information.content %>
        </div>
        <div class="more"><%= link_to "ニュース一覧へ戻る", news_index_path %></div>
      </section>

      <section class="news_list_box related clearfix">
        <div class="head">
          <h3>
            <img class="pc_disp" src="images/news_text_01.png" width="586" height="123" alt="RELATED NEWS 関連ニュース" />
          </h3>
        </div>
        <ul>
          <% @informations.each do |info| %>
          <li class="clearfix">
            <figure class="image"><%= link_to(news_show_path(:id => info.id), :style => "background-image: url(#{image_path info.image})") do %>
                <%= image_tag info.image.to_s, :class => "pc_disp", :width => "600", :height => "440", :alt => "" %>
                <% end %>
            </figure>
            <h3><%= link_to info.title, news_show_path(:id => info.id) %></h3>
            <div class="desc"> <%= info.content.truncate(80) %></div>
            <p class="update"><%= info.updated_at.strftime("%Y.%-m.%-d") %></p>
            <p class="link"><%= link_to 'MORE', news_show_path(:id => info.id) %></p>
          </li>
          <% end %>
        </ul>
      </section>
    </article>
      <!-- コンテンツ終了 -->
    <%= render '/footer' %>
  </div>
</body>